// Generated by Wrangler by running `wrangler types ./types/worker-configuration.d.ts --experimental-include-runtime ./types/runtime.d.ts`

interface Env {
	KV: KVNamespace;
	ENVIRONMENT: "local" | "staging" | "production";
	LOG_LEVEL: "Debug" | "Info";
	COOKIE_SECRET: string;
	STRIPE_SECRET_KEY: string;
	STRIPE_WEBHOOK_SECRET: string;
	D1: D1Database;
	ASSETS: Fetcher;
}
